{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Customer_Update"
	},
	"OnFailure": "/FirstMDKApp/Actions/ClosePage_Cancel.action",
	"OnSuccess": "/FirstMDKApp/Actions/ClosePage_Complete.action",
	"Target": {
		"Service": "/FirstMDKApp/Services/com_sap_edm_sampleservice_v2.service",
		"EntitySet": "Customers",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"EmailAddress": "#Control:FCEmail/#Value",
		"FirstName": "#Control:FCFirstName/#Value",
		"LastName": "#Control:FCLactName/#Value",
		"PhoneNumber": "#Control:FCPhoneNumber/#Value"
	}
}